### ISSUE TITLE
Validating and debugging the result of invalid actions is hard

### ISSUE THREAD

**Issue by tadas-subonis** [elliottneilclark/rs-poker#45] opened 2023-06-02 22:08 UTC
It would be great if there would be some kind of mode that would make bots fold (with a warning) when invalid action is posted.

Now I can get a sequence like:

```
[6sAs][QsAd][KcKd][7h8s][JdQc]b33:f:b20:b20:b20:<>[9h][Ts][Ah]b20:b33:b20:<>[7d]b20:b20:<>[6c]b20:b20:<>
```

One agent raises and the other one can still do "b20" call :)

**Comment by elliottneilclark** [comment] 2023-06-13 06:07
Ohhh that's a bug for sure.

**Comment by elliottneilclark** [comment] 2023-06-14 19:46
@tadas-subonis do you have some more information about the game state when you see this? I added some tests trying to reproduce directly with `GameState` and I haven't gotten that to happen.

Is it possible that b[33] is putting the agent all in? All over-bets are interpreted as going all in. So UTG player had 20 chips remaining, over-bets 33 going all in for a total value of 20. Agents then call down for 20 total?

**Comment by elliottneilclark** [comment] 2023-06-14 23:17
I've run a few fuzz testing passes using the new test to see if raw compute can find something. So far nothing; I'll let it run for a couple of days.

**Comment by elliottneilclark** [comment] 2023-06-22 08:04
@tadas-subonis I have fuzzed for quite a while, and the only thing I can think is that you were seeing overbetting into an all-in. Since that's the most likely I can see, I'll add documentation and explanations. Then close this. 

If there's something else then let me know and I'll open a new issue.

**Comment by elliottneilclark** [comment] 2023-06-23 00:30
I think something different is happening in your example.

`[6sAs][QsAd][KcKd][7h8s][JdQc]b33:f:b20:b20:b20:<>[9h][Ts][Ah]b20:b33:b20:<>[7d]b20:b20:<>[6c]b20:b20:<>`

Notice that from the first round, we have 5 players with actions. One folds, so we would expect to see four players with actions. After the flop though, we only see three actions. Then turn and river we only see 2 players making actions, despite no folds. It looks like `b33` is being rejected entirely, and the agent is being force folded.

**Comment by elliottneilclark** [comment] 2023-07-31 20:47
@tadas-subonis I've released a new beta with logging and all of the other improvements found along the way of this issue.

Thank you again for reporting this. Check out the beta and please give me any feedback that you have

**Closed by elliottneilclark** 2023-07-31 20:47 UTC

**Comment by tadas-subonis** [comment] 2023-07-31 22:21
That looks great. I've already tried and it seems to work fine for now.

Gonna need to play a bit longer.
